config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  root "home#index"

  resources :gossips
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :welcome, only: [:show]
  resources :user, only: [:show]
  resources :city, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name,
    presence: true,
    uniqueness: true
  validates :zip_code,
    presence: true,
    uniqueness: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  
  validates :title, presence: true, length: { in: 3..14 }
  validates :description, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag, optional: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :recipients
  has_many :users, through: :recipients
  
  validates :message, presence: true
  validates :user_id, presence: true
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :user_id, presence: true
  validates :message_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  belongs_to :user

  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :tags
  has_many :recipients
  has_many :messages, through: :recipients
  belongs_to :city, optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :email, 
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = Gossip.joins(user: :city).where(cities: { id: @city.id })
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
    # @user = User.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to gossips_path(@gossip)
      flash[:success] = "Gossip successfully registered"
    else
      flash[:danger] = "Gossip didn't register!"
      render :new
    end
  end

  def index
    redirect_to root_path
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to gossips_path
      flash[:success] = "Gossip successfully edited"
    else
      flash[:danger] = "Gossip didn't edit!"
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :description, :user_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossips = Gossip.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts "$" * 60
    puts params[:id]
    puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/show.html.erb
<!DOCTYPE html>
<html>
  <h1>Welcome Gossip number <%= @gossip.id %></h1>
  <p><strong>Username :</strong> <%= @gossip.user.first_name %></p>
  <p><strong>Title :</strong> <%= @gossip.title%></p>
  <p><strong>Description :</strong> <%= @gossip.description%></p>
  <p><strong>Author :</strong> <%= link_to @gossip.user.first_name, user_path(@gossip.user)%></p>

</html>

app/views/gossips/edit.html.erb
<!DOCTYPE html>
<html>
  <body>
    <% if flash[:danger] %>
    <div class="alert alert-danger">
      <%= flash[:danger] %>
    </div>
  <% end %>
  
    <div class="container mt-5">
        <%= form_for @gossip do |f| %>
      <div class="form-group">
        <label>Titre :</label><br>
        <%= f.text_field :title, class: "form-control" %><br>
      </div>

      <div class="form-group">
        <label for="desc">Contenu :</label><br>
        <%= f.text_area :description, class: "form-control" %><br>
      </div>

      <%= submit_tag "Edit" %>
    <% end %>
    </div>
  </body>
</html>




<!-- 
<body>
    <div class="container mt-5">
        <%= form_tag edit_gossip_path, method: :post do %>
      <div class="form-group">
        <label for="title">Titre :</label><br>
        <%= text_field_tag 'gossip[title]', @gossip.title, class: "form-control" %><br>
      </div>

      <div class="form-group">
        <label for="desc">Contenu :</label><br>
        <%= text_field_tag 'gossip[description]', @gossip.description, class: "form-control" %><br>
      </div>

      <%= submit_tag "Edit" %>
    <% end %>
    </div>
  </body>
-->

app/views/gossips/new.html.erb
<html>
  <body>
  <% if flash[:danger] %>
    <div class="alert alert-danger">
      <%= flash[:danger] %>
    </div>
  <% end %>

<div class="container mt-5">
  <%= form_tag gossips_path, method: :post do %>
  <div class="form-group">
    <label for="title">Titre :</label><br>
    <%= text_field_tag 'gossip[title]', nil, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <label for="desc">Contenu :</label><br>
    <%= text_field_tag 'gossip[description]', nil, class: "form-control" %><br><br>
  </div>

  <div class="form-group">
    <%= label_tag :user_id, "Author" %>
    <%= select_tag 'gossip[user_id]', options_for_select(User.all.collect { |u| [u.first_name, u.id] }), class: "form-control" %>
  </div>

  <%= submit_tag "Submit" %>
  <% end %>
</div>
  </body>
</html>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html>
  <h1>Gossip number <%= @gossip.id %></h1>
  <p><strong>Title :</strong> <%= @gossip.title%></p>
  <p><strong>Description :</strong> <%= @gossip.description%></p>
  <p><strong>Author :</strong> <%= link_to @gossip.user.first_name, user_path(@gossip.user)%></p>
  <p><strong>Author's City :</strong> <%= link_to @gossip.user.city.name, city_path(@gossip.user.city) %></p>

  <div>
  <%= link_to "Edit", edit_gossip_path, class:"btn btn-dark" %>
  </div>
  <br>
  <div>
  <%= button_to "Delete", gossip_path(@gossip), method: :delete, data: {turbo_confirm: 'operate.delete_confirm?'}, class:"btn btn-danger" %>
  </div>
</html>