config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  root "home#index"

  resources :gossips
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :welcome, only: [:show]
  resources :user, only: [:show]
  resources :city, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name,
    presence: true,
    uniqueness: true
  validates :zip_code,
    presence: true,
    uniqueness: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  
  validates :title, presence: true, length: { in: 3..14 }
  validates :description, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag, optional: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :recipients
  has_many :users, through: :recipients
  
  validates :message, presence: true
  validates :user_id, presence: true
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :user_id, presence: true
  validates :message_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  belongs_to :user

  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :tags
  has_many :recipients
  has_many :messages, through: :recipients
  belongs_to :city, optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :email, 
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = Gossip.joins(user: :city).where(cities: { id: @city.id })
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossips = Gossip.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>
    <h1>Contact La team</h1>
    <p>lateam@lateam.com</p>
  </body>
</html>

app/views/contact/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>
    <h1>Contact La team</h1>
    <p>lateam@lateam.com</p>
  </body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
  </head>

  <body>
  <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>

  <div class="jumbotron jumbotron-fluid">
    <div class="container" style="height: 200px;">
      <h1 class="display-4, text-warning-emphasis, text-light">The Gossip Project</h1>
      <br>
      <%= link_to "Create a New Gossip", new_gossip_path , class:"btn btn-dark" %> 
    </div>
  </div>

  <div class="container mt-5">
    <div class="row">
      <% @gossips.each do |gossip| %>
        <div class="col-md-3 mb-3">
          <div class="card">
            <div class="card-header bg-secondary text-dark">Gossip n°<%= gossip.id %></div>
            <div class="card-body">
              <h5 class="card-title"><%= gossip.title %></h5>
              <p class="card-text"><i>Created by:</i> <%= link_to gossip.user.first_name, user_path(gossip.user)%></p>
              <p class="btn btn-light"><%= link_to "Learn More", gossip_path(gossip)%></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <!-- Include Bootstrap JS (optional if you need Bootstrap JavaScript functionality) -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/team/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>
    <h1>La team</h1>
    <ul>
      <li>Elias</li>
      <li>Antoine</li>
      <li>Val</li>
      <li>Enzo</li>
    </ul>
  </body>
</html>

app/views/team/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>
    <h1>La team</h1>
    <ul>
      <li>Elias</li>
      <li>Antoine</li>
      <li>Val</li>
      <li>Sacha (stagiaire avec royalties)</li>
    </ul>
  </body>
</html>