config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  root "home#index"

  resources :gossips
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :welcome, only: [:show]
  resources :user, only: [:show]
  resources :city, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name,
    presence: true,
    uniqueness: true
  validates :zip_code,
    presence: true,
    uniqueness: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  
  validates :title, presence: true, length: { in: 3..14 }
  validates :description, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag, optional: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :recipients
  has_many :users, through: :recipients
  
  validates :message, presence: true
  validates :user_id, presence: true
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :user_id, presence: true
  validates :message_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  belongs_to :user

  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :tags
  has_many :recipients
  has_many :messages, through: :recipients
  belongs_to :city, optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :email, 
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = Gossip.joins(user: :city).where(cities: { id: @city.id })
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossips = Gossip.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css", integrity: "sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js", integrity: "sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js", integrity: "sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd", crossorigin: "anonymous" %> 
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "The Gossip Project", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Create a New Gossip", new_gossip_path , class:"nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Team", team_index_path , class:"nav-link" %> 
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_index_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </nav>

  <%= yield %>

  </body>
</html>